
<script type="text/javascript">
    var placeholder = "Seleccionar";
    
    $(document).ready(function(){
        
        $("#divisa").select2({
            placeholder: placeholder
            , width: 'resolve'
            , allowClear: true
        });
        
        $("#fecha_compra,#fecha_vencimiento").datepicker({
           dateFormat: "yy/mm/dd" 
        });
        
        $("#btnguardar").click(function(){
            var form = {};
            form.monto_t = $("#monto_total").val();
            form.monto_p = $("#monto_pagado").val();
            form.fecha_c = $("#fecha_compra").val();
            form.fecha_v = $("#fecha_vencimiento").val();
            form.divisa = $("#divisa").val();
            $.ajax({
                url:'/application/compra/save'
                ,data:{form:form}
                ,type:'post'
                ,datatype:'json'
                ,async:true
                ,success:function(response){
                    $("#idform")[0].reset();
                    $("#divisa").select2('val','');
                    bootbox.alert('La compra se realizo exitosamente');
                }
            });
        });
        
        
    });
    
</script>
<style type="text/css"> 
    
    .size{
        width: 800px;
        margin: 50px auto;
        text-align: center;
        
    }
    
</style>


<?php
    $title = 'Compra';
    echo $this->headTitle($title);
?>

<blockquote><h1>Compra &nbsp;<span class="glyphicon glyphicon-shopping-cart"></span></h1></blockquote>

<div class="panel panel-primary size">
  <div class="panel-heading">
    <h3 class="panel-title">Formulario de Compra</h3>
  </div>
  <div class="panel-body">
       <form id="idform" class="form-horizontal" role="form">
        <div class="form-group">
            <label for="monto_total" class="col-lg-4 control-label">Monto Total: </label>
            <div class="col-lg-6">
                <input type="text" id="monto_total" class="form-control" placeholder="0.00" name="monto_total">
            </div>
        </div>
        <div class="form-group">
            <label for="monto_pagado" class="col-lg-4 control-label">Monto Pagado: </label>
            <div class="col-lg-6">
                <input type="text" id="monto_pagado" class="form-control" placeholder="0.00" name="monto_pagado">
            </div>
        </div>
        <div class="form-group">
            <label for="fecha_compra" class="col-lg-4 control-label">Fecha de Compra: </label>
            <div class="col-lg-6">
                <input type="text" id="fecha_compra" class="form-control" name="fecha_compra">
            </div>
        </div>
        <div class="form-group">
            <label for="fecha_vencimiento" class="col-lg-4 control-label">Fecha de Vencimiento: </label>
            <div class="col-lg-6">
                <input type="text" id="fecha_vencimiento" class="form-control" name="fecha_vencimiento">
            </div>
        </div>
        <div class="form-group">
            <label for="divisa" class="col-lg-4 control-label">Divisa: </label>
            <div class="col-lg-4">
                <select id="divisa" name="divisa" style="width:230px">
                    <option value=""></option>
                    <option value="Soles">Soles</option>
                    <option value="Dolares">Dolares</option>
                </select>
            </div>
        </div>
        <button id="btnguardar" type="button" class="btn btn-primary">Guardar</button>
    </form>
  </div>
</div>
